### ISSUE TITLE
Enhancement: add a sample for the kcl package managed by kpm.

### ISSUE THREAD

**Issue by zong-zhe** [KusionStack/catalog#20]
### What would you like to be added?

Add an application configuration named 'hellokpm' that can be managed by kpm.

### Why is this needed?

Application configuration development and konfig management can be separated by kpm, the sample "hellokpm" is used to show how to use kpm to manage the development of the application configuration out of the konfig.

**Comment by adohe** [comment]
@zong-zhe is it still required? or maybe we can close it?
